apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: "cdc-connector"
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster2
spec:
  class: io.debezium.connector.mongodb.MongoDbConnector
  tasksMax: 1
  config:
    mongodb.hosts: example-mongodb-0.example-mongodb-svc.mongodb.svc.cluster.local
    mongodb.connection.string: "mongodb://my-user:andy87@example-mongodb-0.example-mongodb-svc.mongodb.svc.cluster.local:27017,example-mongodb-1.example-mongodb-svc.mongodb.svc.cluster.local:27017,example-mongodb-2.example-mongodb-svc.mongodb.svc.cluster.local:27017/admin?replicaSet=example-mongodb&ssl=false"
    mongodb.name: products
    snapshot.mode: never
    mongodb.user: my-user
    mongodb.password: andy87
    collection.include.list: company.product
