apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: "cdc-connector"
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster2
spec:
  class: io.debezium.connector.mongodb.MongoDbConnector
  tasksMax: 1
  config:
    mongodb.hosts: mongodb/example-mongodb-svc:27017
    mongodb.name: products
    snapshot.mode: never
    collection.include.list: company.product
